name: Foundry TOML Check

permissions: {}

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check:
    name: Check foundry.toml
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Check foundry.toml
        uses: awilliams1-cb/foundry-toml-checker@27ee11ed34dfcffda2e6c8e2f36f22c5fcac22ec
