name: SBOM

permissions: {}

on:
  push:
    branches: [main]

jobs:
  sbom:
    name: Submit dependency graph
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
          submodules: recursive

      - uses: awilliams1-cb/sol-deps@174f0f6eeeeb52a83663cd566fc44d3e55d6e7b6
